#!/usr/bin/env python3
"""List code labels whose address is taken (function pointers) as scoped `func` directives.

Ghidra's auto-analysis leaves callbacks and behaviour tables that are only reached
through pointers as bare labels (`&LAB_xxxxxxxx` in the decompiled C). This script
collects them from work/decomp/*.c and writes directives for ApplyAnnotations.java so
that they become functions: addresses below the overlay base are shared by every
program, addresses at or above it are scoped to the program they were found in;
labels of the USA executable (SLUS) are always scoped to it.

Resident functions that only overlays call (for example the pre-fight screen helpers)
are missing from the resident program; the calls in the overlay decompilations
(`*.overlay.c`) add them as shared functions too.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DECOMP = ROOT / "work" / "decomp"
OUT = ROOT / "work" / "ghidra" / "label_funcs.txt"
SYMBOLS = ROOT / "tools" / "ghidra" / "symbols.txt"
OVERLAY_BASE = 0x800B0000
LIBRARY_START = 0x8007A094  # PsyQ runtime from `start`; callbacks there are library-internal
# A taken address used as a value; `(&LAB_x + i)` and `*(T *)(&LAB_x)` are data accesses.
LABEL = re.compile(r"(?<!\)\()&LAB_(8[0-9a-f]{7})(?! \+)")
CALL = re.compile(r"\bFUN_(8[0-9a-f]{7})\(")


def scope_word(c_file: Path) -> str:
    stem = c_file.name.removesuffix(".c")
    return stem.removeprefix("jp_rev1_").removesuffix(".exe")


def main() -> int:
    shared: set[int] = set()
    scoped: dict[str, set[int]] = {}
    for c_file in sorted(DECOMP.glob("*.c")):
        for match in LABEL.finditer(c_file.read_text(errors="replace")):
            addr = int(match.group(1), 16)
            if c_file.name.startswith("SLUS"):
                scoped.setdefault("SLUS", set()).add(addr)
                continue
            if LIBRARY_START <= addr < OVERLAY_BASE:
                continue
            if addr < OVERLAY_BASE:
                shared.add(addr)
            else:
                scoped.setdefault(scope_word(c_file), set()).add(addr)
    for c_file in sorted(DECOMP.glob("*.overlay.c")):
        for match in CALL.finditer(c_file.read_text(errors="replace")):
            addr = int(match.group(1), 16)
            if addr < LIBRARY_START:
                shared.add(addr)
    named = {int(line.split()[1], 16) for line in SYMBOLS.read_text().splitlines()
             if line.startswith("func") and len(line.split()) >= 3}
    shared -= named
    lines = ["# generated by tools/ghidra/label_funcs.py"]
    lines += [f"func {a:08x} FUN_{a:08x}" for a in sorted(shared)]
    for word, addrs in sorted(scoped.items()):
        lines += [f"func@{word} {a:08x} FUN_{a:08x}" for a in sorted(addrs)]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(shared)} shared, {sum(map(len, scoped.values()))} overlay-scoped -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
